// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMh2j_ZgSHm1c8mXo5L7Ko4-6y_zMW7BQ',
    appId: '1:1065997490171:web:e8963facb8eaa48e94dd5e',
    messagingSenderId: '1065997490171',
    projectId: 'surveyor-26ae5',
    authDomain: 'surveyor-26ae5.firebaseapp.com',
    storageBucket: 'surveyor-26ae5.appspot.com',
    measurementId: 'G-3Z3ZYPVBD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYyzHR0mbxjofbGJFZ2T9Xy32kxZmcvNo',
    appId: '1:1065997490171:android:8a9aeda5d68c3b5394dd5e',
    messagingSenderId: '1065997490171',
    projectId: 'surveyor-26ae5',
    storageBucket: 'surveyor-26ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcgC_U_rmmFfaBEo3V1VtQLwsc5bpjcdo',
    appId: '1:1065997490171:ios:82cfa6adb681e73494dd5e',
    messagingSenderId: '1065997490171',
    projectId: 'surveyor-26ae5',
    storageBucket: 'surveyor-26ae5.appspot.com',
    iosBundleId: 'com.example.surveyorClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcgC_U_rmmFfaBEo3V1VtQLwsc5bpjcdo',
    appId: '1:1065997490171:ios:bb5f29381733381b94dd5e',
    messagingSenderId: '1065997490171',
    projectId: 'surveyor-26ae5',
    storageBucket: 'surveyor-26ae5.appspot.com',
    iosBundleId: 'com.example.surveyorClone.RunnerTests',
  );
}
